<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) { @session_start(); }
function h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES|ENT_SUBSTITUTE, 'UTF-8'); }
function jarvis_data_path(string $s=''): string { $b='/var/www/data'; return $s ? $b.'/'.ltrim($s,'/') : $b; }
function jarvis_log_file(): string { return jarvis_data_path('logs/actions.log'); }
function jarvis_append_log(string $type,string $target,string $status,string $details=''): void { @file_put_contents(jarvis_log_file(), sprintf("[%s] type=%s target=%s status=%s details=%s\n", date('c'),$type,$target,$status,preg_replace('/\s+/',' ',trim($details))), FILE_APPEND); }
function jarvis_render_notice(string $m,string $type='warning'): string { return '<div class="notice '.h($type).'">'.$m.'</div>'; }
function jarvis_csrf_token(): string { if(empty($_SESSION['jarvis_csrf_token'])) $_SESSION['jarvis_csrf_token']=bin2hex(random_bytes(16)); return $_SESSION['jarvis_csrf_token']; }
function jarvis_csrf_input(): string { return '<input type="hidden" name="csrf_token" value="'.h(jarvis_csrf_token()).'">'; }
function jarvis_check_csrf(): void { $t=$_POST['csrf_token']??''; if(!is_string($t)||!hash_equals(jarvis_csrf_token(),$t)) throw new RuntimeException('Jeton CSRF invalide.'); }
function env_all(): array { $e=getenv(); if(!is_array($e))$e=[]; foreach($_SERVER as $k=>$v){ if(is_string($v)&&preg_match('/^[A-Z0-9_]+$/',$k)&&!array_key_exists($k,$e)) $e[$k]=$v; } ksort($e); return $e; }
function env_value(string $k): ?string { $v=getenv($k); if($v!==false) return (string)$v; return isset($_SERVER[$k])&&is_string($_SERVER[$k])?$_SERVER[$k]:null; }
function db(): PDO { $host=env_value('JARVIS_PG_HOST') ?: 'jarvis_postgres'; $name=env_value('JARVIS_PG_DB') ?: 'jarvis_memory'; $user=env_value('JARVIS_PG_USER') ?: 'n8n'; $pass=env_value('JARVIS_PG_PASSWORD') ?: ''; $port=env_value('JARVIS_PG_PORT') ?: '5432'; return new PDO("pgsql:host=$host;port=$port;dbname=$name",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
function db_try(): array { try{$pdo=db();$v=$pdo->query('select version() as version')->fetch();return ['ok'=>true,'pdo'=>$pdo,'message'=>$v['version']??'OK'];}catch(Throwable $e){return ['ok'=>false,'pdo'=>null,'message'=>$e->getMessage()];} }
function table_exists(PDO $pdo,string $t): bool { $s=$pdo->prepare('select exists(select 1 from information_schema.tables where table_schema=current_schema() and table_name=:t) as e');$s->execute(['t'=>$t]);$r=$s->fetch(); return !empty($r['e']); }
function scripts_root(): string { return '/var/www/data/scripts'; }
function safe_script_rel(string $rel): string { $rel=trim(str_replace('\\','/',$rel)); if($rel===''||str_starts_with($rel,'/')||str_contains($rel,'../')) throw new RuntimeException('Chemin script invalide.'); if(!preg_match('#^[a-zA-Z0-9._/-]+$#',$rel)) throw new RuntimeException('Chemin script invalide.'); return $rel; }
function script_abs(string $rel): string { return scripts_root().'/'.safe_script_rel($rel); }
function sql_abs(string $rel): string { return jarvis_data_path('sql/postgres/'.basename($rel)); }
function validate_required_env_json(string $json): array { if(trim($json)==='') return []; $d=json_decode($json,true); if(!is_array($d)) throw new RuntimeException('required_env_json doit être un tableau JSON.'); foreach($d as $x){ if(!is_string($x)||$x==='') throw new RuntimeException('required_env_json doit contenir des chaînes non vides.'); } return array_values($d); }
function validate_params_json(string $json): array { if(trim($json)==='') return []; $d=json_decode($json,true); if(!is_array($d)) throw new RuntimeException('params doit être un JSON objet.'); foreach($d as $k=>$v){ if(!is_string($k)||$k==='') throw new RuntimeException('Clé params invalide.'); if(is_array($v)||is_object($v)) throw new RuntimeException('Valeurs params scalaires uniquement.'); } return $d; }
function registry_all(PDO $pdo): array { return $pdo->query("select script_name,file_name,coalesce(description,'') as description,required_env_json,is_active,updated_at from jarvis_script_registry order by script_name")->fetchAll(); }
function registry_exists(PDO $pdo,string $name): bool { $s=$pdo->prepare('select 1 from jarvis_script_registry where script_name=:n');$s->execute(['n'=>$name]); return (bool)$s->fetchColumn(); }
function registry_add(PDO $pdo,string $name,string $file,string $desc,array $req,bool $active): void { $s=$pdo->prepare('insert into jarvis_script_registry(script_name,file_name,description,required_env_json,is_active,updated_at) values(:n,:f,:d,cast(:j as jsonb),:a,now())'); $s->execute(['n'=>$name,'f'=>$file,'d'=>$desc,'j'=>json_encode($req,JSON_UNESCAPED_SLASHES),'a'=>$active]); }
function registry_toggle(PDO $pdo,string $name): void { $s=$pdo->prepare('update jarvis_script_registry set is_active=not is_active, updated_at=now() where script_name=:n');$s->execute(['n'=>$name]); }
function registry_delete(PDO $pdo,string $name): void { $s=$pdo->prepare('delete from jarvis_script_registry where script_name=:n');$s->execute(['n'=>$name]); }
function scan_scripts(): array { $root=scripts_root(); $out=[]; if(!is_dir($root)) return $out; $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)); foreach($it as $file){ if($file->isFile()){ $rel=str_replace($root.'/','',$file->getPathname()); if(preg_match('#^[a-zA-Z0-9._/-]+$#',$rel)) $out[]=$rel; } } sort($out); return $out; }
function precheck(PDO $pdo,string $scriptName): array { $s=$pdo->prepare("select script_name,file_name,coalesce(description,'') as description,required_env_json,is_active,updated_at from jarvis_script_registry where script_name=:n"); $s->execute(['n'=>$scriptName]); $row=$s->fetch(); if(!$row) throw new RuntimeException('Script introuvable dans la registry.'); $req=json_decode((string)$row['required_env_json'],true); if(!is_array($req)) $req=[]; $env=env_all(); $missing=[]; foreach($req as $k){ if(!array_key_exists((string)$k,$env)) $missing[]=(string)$k; } $active=((string)$row['is_active']!=='0' && strtolower((string)$row['is_active'])!=='false'); $fileFound=is_file(script_abs((string)$row['file_name'])); return ['row'=>$row,'missing'=>$missing,'active'=>$active,'file_found'=>$fileFound]; }
function build_cmd(string $fileName,string $phase,bool $confirmed,array $params): string { $parts=['bash',escapeshellarg(script_abs($fileName)),'--phase',escapeshellarg($phase),'--confirmed',escapeshellarg($confirmed?'true':'false')]; foreach($params as $k=>$v){ $parts[]='--param'; $parts[]=escapeshellarg((string)$k.'='.(string)$v); } return implode(' ',$parts); }
function services_default(): array { return [['name'=>'OpenWebUI','url'=>'http://jarvis_openwebui:8080'],['name'=>'Ollama','url'=>'http://jarvis_ollama:11434'],['name'=>'MCPO','url'=>'http://jarvis_mcpo:8000']]; }
function http_check(string $url): array { $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_TIMEOUT=>4,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_SSL_VERIFYPEER=>false,CURLOPT_SSL_VERIFYHOST=>false]); $start=microtime(true); $body=curl_exec($ch); $errno=curl_errno($ch); $error=curl_error($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $ms=(int)round((microtime(true)-$start)*1000); curl_close($ch); return ['ok'=>$errno===0&&$code>0&&$code<500,'code'=>$code,'ms'=>$ms,'error'=>$error,'body'=>(string)$body]; }
