<?php require_once __DIR__.'/../inc/bootstrap.php'; $d=db_try(); if(!$d['ok']){ echo jarvis_render_notice('<pre>'.h($d['message']).'</pre>','error'); exit; } $pdo=$d['pdo']; if(!table_exists($pdo,'jarvis_script_registry')){ echo jarvis_render_notice('La table <code>jarvis_script_registry</code> n’existe pas. Lance le SQL fourni.','warning'); exit; } $msg=''; $type='success'; try{ if($_SERVER['REQUEST_METHOD']==='POST'){ jarvis_check_csrf(); $a=(string)($_POST['form_action']??''); if($a==='add'){ $sn=trim((string)($_POST['script_name']??'')); $fn=trim((string)($_POST['file_name']??'')); $desc=trim((string)($_POST['description']??'')); $req=trim((string)($_POST['required_env_json']??'[]')); $active=isset($_POST['is_active']); if($sn===''||$fn==='') throw new RuntimeException('script_name et file_name sont obligatoires.'); if(!preg_match('/^[a-zA-Z0-9._-]+$/',$sn)) throw new RuntimeException('script_name invalide.'); safe_script_rel($fn); $envs=validate_required_env_json($req); if(registry_exists($pdo,$sn)) throw new RuntimeException('Doublon script_name.'); registry_add($pdo,$sn,$fn,$desc,$envs,$active); $msg='Script ajouté.'; jarvis_append_log('scripts-admin',$sn,'added',$fn);} elseif($a==='toggle'){ registry_toggle($pdo,(string)$_POST['script_name']); $msg='État mis à jour.'; } elseif($a==='delete'){ registry_delete($pdo,(string)$_POST['script_name']); $msg='Script supprimé.'; } } }catch(Throwable $e){ $msg=$e->getMessage(); $type='error'; } $rows=registry_all($pdo); $dbFiles=array_map(fn($r)=>(string)$r['file_name'],$rows); $missing=array_values(array_diff(scan_scripts(),$dbFiles)); ?>
<div class="stack">
  <div class="notice">Gestion DB des scripts autorisés. Ici, on administre la registry, on ne lance rien.</div>
  <?php if($msg!==''): ?><?= jarvis_render_notice(h($msg),$type) ?><?php endif; ?>
  <div class="card"><h3>Scripts enregistrés</h3><table><thead><tr><th>script_name</th><th>file_name</th><th>description</th><th>required_env_json</th><th>actif</th><th>fichier</th><th>actions</th></tr></thead><tbody><?php foreach($rows as $r): $found=is_file(script_abs((string)$r['file_name'])); ?><tr><td><strong><?= h($r['script_name']) ?></strong></td><td><code><?= h($r['file_name']) ?></code></td><td><?= h($r['description']) ?></td><td><pre><?= h((string)$r['required_env_json']) ?></pre></td><td><span class="status <?= ((bool)$r['is_active'])?'up':'warn' ?>"><?= ((bool)$r['is_active'])?'YES':'NO' ?></span></td><td><span class="status <?= $found?'up':'down' ?>"><?= $found?'TROUVÉ':'MANQUANT' ?></span></td><td><div class="actions"><form method="post"><?= jarvis_csrf_input() ?><input type="hidden" name="form_action" value="toggle"><input type="hidden" name="script_name" value="<?= h($r['script_name']) ?>"><button class="ghost-btn" type="submit"><?= ((bool)$r['is_active'])?'Désactiver':'Activer' ?></button></form><form method="post"><?= jarvis_csrf_input() ?><input type="hidden" name="form_action" value="delete"><input type="hidden" name="script_name" value="<?= h($r['script_name']) ?>"><button class="danger-btn" type="submit" data-confirm="Supprimer <?= h($r['script_name']) ?> ?">Supprimer</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
  <div class="two">
    <div class="card"><h3>Scripts présents sur disque mais absents de la DB</h3><?php if(!$missing): ?><p class="small">Aucun fichier orphelin détecté.</p><?php else: ?><table><thead><tr><th>fichier</th><th>action</th></tr></thead><tbody><?php foreach($missing as $f): ?><tr><td><code><?= h($f) ?></code></td><td><button class="ghost-btn" type="button" data-prefill-script="<?= h($f) ?>">Préremplir</button></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
    <div class="card"><h3>Ajouter un script</h3><form method="post"><?= jarvis_csrf_input() ?><input type="hidden" name="form_action" value="add"><p><label>script_name</label><input id="script_name" name="script_name" type="text" placeholder="mon-import.sh"></p><p><label>file_name</label><input id="file_name" name="file_name" type="text" placeholder="import/mon-import.sh"></p><p><label>description</label><input name="description" type="text" placeholder="Description lisible du script"></p><p><label>required_env_json</label><textarea name="required_env_json">[]</textarea></p><p><label><input type="checkbox" name="is_active" value="1" checked> Actif</label></p><div class="actions"><button class="primary-btn" type="submit">Ajouter</button></div></form></div>
  </div>
</div>
